// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jianbo-zh/jydata/database/ent/appversion"
	"github.com/jianbo-zh/jydata/database/ent/predicate"
)

// AppVersionDelete is the builder for deleting a AppVersion entity.
type AppVersionDelete struct {
	config
	hooks    []Hook
	mutation *AppVersionMutation
}

// Where appends a list predicates to the AppVersionDelete builder.
func (avd *AppVersionDelete) Where(ps ...predicate.AppVersion) *AppVersionDelete {
	avd.mutation.Where(ps...)
	return avd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (avd *AppVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, avd.sqlExec, avd.mutation, avd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (avd *AppVersionDelete) ExecX(ctx context.Context) int {
	n, err := avd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (avd *AppVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(appversion.Table, sqlgraph.NewFieldSpec(appversion.FieldID, field.TypeInt))
	if ps := avd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, avd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	avd.mutation.done = true
	return affected, err
}

// AppVersionDeleteOne is the builder for deleting a single AppVersion entity.
type AppVersionDeleteOne struct {
	avd *AppVersionDelete
}

// Where appends a list predicates to the AppVersionDelete builder.
func (avdo *AppVersionDeleteOne) Where(ps ...predicate.AppVersion) *AppVersionDeleteOne {
	avdo.avd.mutation.Where(ps...)
	return avdo
}

// Exec executes the deletion query.
func (avdo *AppVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := avdo.avd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (avdo *AppVersionDeleteOne) ExecX(ctx context.Context) {
	if err := avdo.Exec(ctx); err != nil {
		panic(err)
	}
}
