// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"github.com/jianbo-zh/jydata/database/ent/car"
	"github.com/jianbo-zh/jydata/database/ent/carconfig"
	"github.com/jianbo-zh/jydata/database/ent/carconfigdownload"
	"github.com/jianbo-zh/jydata/database/ent/carsmodels"
	"github.com/jianbo-zh/jydata/database/ent/carsoperatelog"
	"github.com/jianbo-zh/jydata/database/ent/order"
	"github.com/jianbo-zh/jydata/database/ent/predicate"
	"github.com/jianbo-zh/jydata/database/ent/scenicarea"
	"github.com/jianbo-zh/jydata/database/ent/schetask"
	"github.com/jianbo-zh/jydata/database/ent/statshourlycar"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CarQuery is the builder for querying Car entities.
type CarQuery struct {
	config
	ctx                      *QueryContext
	order                    []car.OrderOption
	inters                   []Interceptor
	predicates               []predicate.Car
	withBackgroundScenicArea *ScenicAreaQuery
	withCarsModels           *CarsModelsQuery
	withCarOperateLogs       *CarsOperateLogQuery
	withOrders               *OrderQuery
	withStatsHourlyCar       *StatsHourlyCarQuery
	withScheTask             *ScheTaskQuery
	withConfigFiles          *CarConfigQuery
	withCarConfigs           *CarConfigDownloadQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CarQuery builder.
func (cq *CarQuery) Where(ps ...predicate.Car) *CarQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CarQuery) Limit(limit int) *CarQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CarQuery) Offset(offset int) *CarQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CarQuery) Unique(unique bool) *CarQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CarQuery) Order(o ...car.OrderOption) *CarQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryBackgroundScenicArea chains the current query on the "background_scenic_area" edge.
func (cq *CarQuery) QueryBackgroundScenicArea() *ScenicAreaQuery {
	query := (&ScenicAreaClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(scenicarea.Table, scenicarea.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, car.BackgroundScenicAreaTable, car.BackgroundScenicAreaColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCarsModels chains the current query on the "cars_models" edge.
func (cq *CarQuery) QueryCarsModels() *CarsModelsQuery {
	query := (&CarsModelsClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(carsmodels.Table, carsmodels.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, car.CarsModelsTable, car.CarsModelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCarOperateLogs chains the current query on the "car_operate_logs" edge.
func (cq *CarQuery) QueryCarOperateLogs() *CarsOperateLogQuery {
	query := (&CarsOperateLogClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(carsoperatelog.Table, carsoperatelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, car.CarOperateLogsTable, car.CarOperateLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrders chains the current query on the "orders" edge.
func (cq *CarQuery) QueryOrders() *OrderQuery {
	query := (&OrderClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, car.OrdersTable, car.OrdersColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStatsHourlyCar chains the current query on the "stats_hourly_car" edge.
func (cq *CarQuery) QueryStatsHourlyCar() *StatsHourlyCarQuery {
	query := (&StatsHourlyCarClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(statshourlycar.Table, statshourlycar.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, car.StatsHourlyCarTable, car.StatsHourlyCarColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScheTask chains the current query on the "sche_task" edge.
func (cq *CarQuery) QueryScheTask() *ScheTaskQuery {
	query := (&ScheTaskClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(schetask.Table, schetask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, car.ScheTaskTable, car.ScheTaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConfigFiles chains the current query on the "config_files" edge.
func (cq *CarQuery) QueryConfigFiles() *CarConfigQuery {
	query := (&CarConfigClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(carconfig.Table, carconfig.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, car.ConfigFilesTable, car.ConfigFilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCarConfigs chains the current query on the "car_configs" edge.
func (cq *CarQuery) QueryCarConfigs() *CarConfigDownloadQuery {
	query := (&CarConfigDownloadClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(car.Table, car.FieldID, selector),
			sqlgraph.To(carconfigdownload.Table, carconfigdownload.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, car.CarConfigsTable, car.CarConfigsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Car entity from the query.
// Returns a *NotFoundError when no Car was found.
func (cq *CarQuery) First(ctx context.Context) (*Car, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{car.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CarQuery) FirstX(ctx context.Context) *Car {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Car ID from the query.
// Returns a *NotFoundError when no Car ID was found.
func (cq *CarQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{car.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CarQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Car entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Car entity is found.
// Returns a *NotFoundError when no Car entities are found.
func (cq *CarQuery) Only(ctx context.Context) (*Car, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{car.Label}
	default:
		return nil, &NotSingularError{car.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CarQuery) OnlyX(ctx context.Context) *Car {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Car ID in the query.
// Returns a *NotSingularError when more than one Car ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CarQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{car.Label}
	default:
		err = &NotSingularError{car.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CarQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Cars.
func (cq *CarQuery) All(ctx context.Context) ([]*Car, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Car, *CarQuery]()
	return withInterceptors[[]*Car](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CarQuery) AllX(ctx context.Context) []*Car {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Car IDs.
func (cq *CarQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(car.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CarQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CarQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CarQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CarQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CarQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CarQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CarQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CarQuery) Clone() *CarQuery {
	if cq == nil {
		return nil
	}
	return &CarQuery{
		config:                   cq.config,
		ctx:                      cq.ctx.Clone(),
		order:                    append([]car.OrderOption{}, cq.order...),
		inters:                   append([]Interceptor{}, cq.inters...),
		predicates:               append([]predicate.Car{}, cq.predicates...),
		withBackgroundScenicArea: cq.withBackgroundScenicArea.Clone(),
		withCarsModels:           cq.withCarsModels.Clone(),
		withCarOperateLogs:       cq.withCarOperateLogs.Clone(),
		withOrders:               cq.withOrders.Clone(),
		withStatsHourlyCar:       cq.withStatsHourlyCar.Clone(),
		withScheTask:             cq.withScheTask.Clone(),
		withConfigFiles:          cq.withConfigFiles.Clone(),
		withCarConfigs:           cq.withCarConfigs.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithBackgroundScenicArea tells the query-builder to eager-load the nodes that are connected to
// the "background_scenic_area" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithBackgroundScenicArea(opts ...func(*ScenicAreaQuery)) *CarQuery {
	query := (&ScenicAreaClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withBackgroundScenicArea = query
	return cq
}

// WithCarsModels tells the query-builder to eager-load the nodes that are connected to
// the "cars_models" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithCarsModels(opts ...func(*CarsModelsQuery)) *CarQuery {
	query := (&CarsModelsClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withCarsModels = query
	return cq
}

// WithCarOperateLogs tells the query-builder to eager-load the nodes that are connected to
// the "car_operate_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithCarOperateLogs(opts ...func(*CarsOperateLogQuery)) *CarQuery {
	query := (&CarsOperateLogClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withCarOperateLogs = query
	return cq
}

// WithOrders tells the query-builder to eager-load the nodes that are connected to
// the "orders" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithOrders(opts ...func(*OrderQuery)) *CarQuery {
	query := (&OrderClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withOrders = query
	return cq
}

// WithStatsHourlyCar tells the query-builder to eager-load the nodes that are connected to
// the "stats_hourly_car" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithStatsHourlyCar(opts ...func(*StatsHourlyCarQuery)) *CarQuery {
	query := (&StatsHourlyCarClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withStatsHourlyCar = query
	return cq
}

// WithScheTask tells the query-builder to eager-load the nodes that are connected to
// the "sche_task" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithScheTask(opts ...func(*ScheTaskQuery)) *CarQuery {
	query := (&ScheTaskClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withScheTask = query
	return cq
}

// WithConfigFiles tells the query-builder to eager-load the nodes that are connected to
// the "config_files" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithConfigFiles(opts ...func(*CarConfigQuery)) *CarQuery {
	query := (&CarConfigClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withConfigFiles = query
	return cq
}

// WithCarConfigs tells the query-builder to eager-load the nodes that are connected to
// the "car_configs" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CarQuery) WithCarConfigs(opts ...func(*CarConfigDownloadQuery)) *CarQuery {
	query := (&CarConfigDownloadClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withCarConfigs = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeleteTime time.Time `json:"delete_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Car.Query().
//		GroupBy(car.FieldDeleteTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CarQuery) GroupBy(field string, fields ...string) *CarGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CarGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = car.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeleteTime time.Time `json:"delete_time,omitempty"`
//	}
//
//	client.Car.Query().
//		Select(car.FieldDeleteTime).
//		Scan(ctx, &v)
func (cq *CarQuery) Select(fields ...string) *CarSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CarSelect{CarQuery: cq}
	sbuild.label = car.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CarSelect configured with the given aggregations.
func (cq *CarQuery) Aggregate(fns ...AggregateFunc) *CarSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CarQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !car.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CarQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Car, error) {
	var (
		nodes       = []*Car{}
		_spec       = cq.querySpec()
		loadedTypes = [8]bool{
			cq.withBackgroundScenicArea != nil,
			cq.withCarsModels != nil,
			cq.withCarOperateLogs != nil,
			cq.withOrders != nil,
			cq.withStatsHourlyCar != nil,
			cq.withScheTask != nil,
			cq.withConfigFiles != nil,
			cq.withCarConfigs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Car).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Car{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withBackgroundScenicArea; query != nil {
		if err := cq.loadBackgroundScenicArea(ctx, query, nodes, nil,
			func(n *Car, e *ScenicArea) { n.Edges.BackgroundScenicArea = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCarsModels; query != nil {
		if err := cq.loadCarsModels(ctx, query, nodes, nil,
			func(n *Car, e *CarsModels) { n.Edges.CarsModels = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCarOperateLogs; query != nil {
		if err := cq.loadCarOperateLogs(ctx, query, nodes,
			func(n *Car) { n.Edges.CarOperateLogs = []*CarsOperateLog{} },
			func(n *Car, e *CarsOperateLog) { n.Edges.CarOperateLogs = append(n.Edges.CarOperateLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withOrders; query != nil {
		if err := cq.loadOrders(ctx, query, nodes,
			func(n *Car) { n.Edges.Orders = []*Order{} },
			func(n *Car, e *Order) { n.Edges.Orders = append(n.Edges.Orders, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withStatsHourlyCar; query != nil {
		if err := cq.loadStatsHourlyCar(ctx, query, nodes,
			func(n *Car) { n.Edges.StatsHourlyCar = []*StatsHourlyCar{} },
			func(n *Car, e *StatsHourlyCar) { n.Edges.StatsHourlyCar = append(n.Edges.StatsHourlyCar, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withScheTask; query != nil {
		if err := cq.loadScheTask(ctx, query, nodes,
			func(n *Car) { n.Edges.ScheTask = []*ScheTask{} },
			func(n *Car, e *ScheTask) { n.Edges.ScheTask = append(n.Edges.ScheTask, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withConfigFiles; query != nil {
		if err := cq.loadConfigFiles(ctx, query, nodes,
			func(n *Car) { n.Edges.ConfigFiles = []*CarConfig{} },
			func(n *Car, e *CarConfig) { n.Edges.ConfigFiles = append(n.Edges.ConfigFiles, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withCarConfigs; query != nil {
		if err := cq.loadCarConfigs(ctx, query, nodes,
			func(n *Car) { n.Edges.CarConfigs = []*CarConfigDownload{} },
			func(n *Car, e *CarConfigDownload) { n.Edges.CarConfigs = append(n.Edges.CarConfigs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CarQuery) loadBackgroundScenicArea(ctx context.Context, query *ScenicAreaQuery, nodes []*Car, init func(*Car), assign func(*Car, *ScenicArea)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Car)
	for i := range nodes {
		fk := nodes[i].ScenicAreaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(scenicarea.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "scenic_area_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CarQuery) loadCarsModels(ctx context.Context, query *CarsModelsQuery, nodes []*Car, init func(*Car), assign func(*Car, *CarsModels)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Car)
	for i := range nodes {
		fk := nodes[i].ModelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(carsmodels.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CarQuery) loadCarOperateLogs(ctx context.Context, query *CarsOperateLogQuery, nodes []*Car, init func(*Car), assign func(*Car, *CarsOperateLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Car)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(carsoperatelog.FieldCarID)
	}
	query.Where(predicate.CarsOperateLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(car.CarOperateLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CarID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "car_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CarQuery) loadOrders(ctx context.Context, query *OrderQuery, nodes []*Car, init func(*Car), assign func(*Car, *Order)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Car)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(order.FieldCarID)
	}
	query.Where(predicate.Order(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(car.OrdersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CarID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "car_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CarQuery) loadStatsHourlyCar(ctx context.Context, query *StatsHourlyCarQuery, nodes []*Car, init func(*Car), assign func(*Car, *StatsHourlyCar)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Car)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(statshourlycar.FieldCarID)
	}
	query.Where(predicate.StatsHourlyCar(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(car.StatsHourlyCarColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CarID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "car_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CarQuery) loadScheTask(ctx context.Context, query *ScheTaskQuery, nodes []*Car, init func(*Car), assign func(*Car, *ScheTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Car)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(schetask.FieldCarID)
	}
	query.Where(predicate.ScheTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(car.ScheTaskColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CarID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "car_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CarQuery) loadConfigFiles(ctx context.Context, query *CarConfigQuery, nodes []*Car, init func(*Car), assign func(*Car, *CarConfig)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Car)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(carconfig.FieldCarID)
	}
	query.Where(predicate.CarConfig(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(car.ConfigFilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CarID
		if fk == nil {
			return fmt.Errorf(`foreign-key "car_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "car_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CarQuery) loadCarConfigs(ctx context.Context, query *CarConfigDownloadQuery, nodes []*Car, init func(*Car), assign func(*Car, *CarConfigDownload)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Car)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CarConfigDownload(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(car.CarConfigsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.car_car_configs
		if fk == nil {
			return fmt.Errorf(`foreign-key "car_car_configs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "car_car_configs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CarQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CarQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(car.Table, car.Columns, sqlgraph.NewFieldSpec(car.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, car.FieldID)
		for i := range fields {
			if fields[i] != car.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if cq.withBackgroundScenicArea != nil {
			_spec.Node.AddColumnOnce(car.FieldScenicAreaID)
		}
		if cq.withCarsModels != nil {
			_spec.Node.AddColumnOnce(car.FieldModelID)
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CarQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(car.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = car.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CarGroupBy is the group-by builder for Car entities.
type CarGroupBy struct {
	selector
	build *CarQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CarGroupBy) Aggregate(fns ...AggregateFunc) *CarGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CarGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarQuery, *CarGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CarGroupBy) sqlScan(ctx context.Context, root *CarQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CarSelect is the builder for selecting fields of Car entities.
type CarSelect struct {
	*CarQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CarSelect) Aggregate(fns ...AggregateFunc) *CarSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CarSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarQuery, *CarSelect](ctx, cs.CarQuery, cs, cs.inters, v)
}

func (cs *CarSelect) sqlScan(ctx context.Context, root *CarQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
