// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jianbo-zh/jydata/database/ent/carextendyokee"
	"github.com/jianbo-zh/jydata/database/ent/predicate"
)

// CarExtendYokeeQuery is the builder for querying CarExtendYokee entities.
type CarExtendYokeeQuery struct {
	config
	ctx        *QueryContext
	order      []carextendyokee.OrderOption
	inters     []Interceptor
	predicates []predicate.CarExtendYokee
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CarExtendYokeeQuery builder.
func (ceyq *CarExtendYokeeQuery) Where(ps ...predicate.CarExtendYokee) *CarExtendYokeeQuery {
	ceyq.predicates = append(ceyq.predicates, ps...)
	return ceyq
}

// Limit the number of records to be returned by this query.
func (ceyq *CarExtendYokeeQuery) Limit(limit int) *CarExtendYokeeQuery {
	ceyq.ctx.Limit = &limit
	return ceyq
}

// Offset to start from.
func (ceyq *CarExtendYokeeQuery) Offset(offset int) *CarExtendYokeeQuery {
	ceyq.ctx.Offset = &offset
	return ceyq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ceyq *CarExtendYokeeQuery) Unique(unique bool) *CarExtendYokeeQuery {
	ceyq.ctx.Unique = &unique
	return ceyq
}

// Order specifies how the records should be ordered.
func (ceyq *CarExtendYokeeQuery) Order(o ...carextendyokee.OrderOption) *CarExtendYokeeQuery {
	ceyq.order = append(ceyq.order, o...)
	return ceyq
}

// First returns the first CarExtendYokee entity from the query.
// Returns a *NotFoundError when no CarExtendYokee was found.
func (ceyq *CarExtendYokeeQuery) First(ctx context.Context) (*CarExtendYokee, error) {
	nodes, err := ceyq.Limit(1).All(setContextOp(ctx, ceyq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{carextendyokee.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) FirstX(ctx context.Context) *CarExtendYokee {
	node, err := ceyq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CarExtendYokee ID from the query.
// Returns a *NotFoundError when no CarExtendYokee ID was found.
func (ceyq *CarExtendYokeeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ceyq.Limit(1).IDs(setContextOp(ctx, ceyq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{carextendyokee.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) FirstIDX(ctx context.Context) int {
	id, err := ceyq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CarExtendYokee entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CarExtendYokee entity is found.
// Returns a *NotFoundError when no CarExtendYokee entities are found.
func (ceyq *CarExtendYokeeQuery) Only(ctx context.Context) (*CarExtendYokee, error) {
	nodes, err := ceyq.Limit(2).All(setContextOp(ctx, ceyq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{carextendyokee.Label}
	default:
		return nil, &NotSingularError{carextendyokee.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) OnlyX(ctx context.Context) *CarExtendYokee {
	node, err := ceyq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CarExtendYokee ID in the query.
// Returns a *NotSingularError when more than one CarExtendYokee ID is found.
// Returns a *NotFoundError when no entities are found.
func (ceyq *CarExtendYokeeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ceyq.Limit(2).IDs(setContextOp(ctx, ceyq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{carextendyokee.Label}
	default:
		err = &NotSingularError{carextendyokee.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) OnlyIDX(ctx context.Context) int {
	id, err := ceyq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CarExtendYokees.
func (ceyq *CarExtendYokeeQuery) All(ctx context.Context) ([]*CarExtendYokee, error) {
	ctx = setContextOp(ctx, ceyq.ctx, ent.OpQueryAll)
	if err := ceyq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CarExtendYokee, *CarExtendYokeeQuery]()
	return withInterceptors[[]*CarExtendYokee](ctx, ceyq, qr, ceyq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) AllX(ctx context.Context) []*CarExtendYokee {
	nodes, err := ceyq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CarExtendYokee IDs.
func (ceyq *CarExtendYokeeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ceyq.ctx.Unique == nil && ceyq.path != nil {
		ceyq.Unique(true)
	}
	ctx = setContextOp(ctx, ceyq.ctx, ent.OpQueryIDs)
	if err = ceyq.Select(carextendyokee.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) IDsX(ctx context.Context) []int {
	ids, err := ceyq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ceyq *CarExtendYokeeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ceyq.ctx, ent.OpQueryCount)
	if err := ceyq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ceyq, querierCount[*CarExtendYokeeQuery](), ceyq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) CountX(ctx context.Context) int {
	count, err := ceyq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ceyq *CarExtendYokeeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ceyq.ctx, ent.OpQueryExist)
	switch _, err := ceyq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ceyq *CarExtendYokeeQuery) ExistX(ctx context.Context) bool {
	exist, err := ceyq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CarExtendYokeeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ceyq *CarExtendYokeeQuery) Clone() *CarExtendYokeeQuery {
	if ceyq == nil {
		return nil
	}
	return &CarExtendYokeeQuery{
		config:     ceyq.config,
		ctx:        ceyq.ctx.Clone(),
		order:      append([]carextendyokee.OrderOption{}, ceyq.order...),
		inters:     append([]Interceptor{}, ceyq.inters...),
		predicates: append([]predicate.CarExtendYokee{}, ceyq.predicates...),
		// clone intermediate query.
		sql:  ceyq.sql.Clone(),
		path: ceyq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeleteTime time.Time `json:"delete_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CarExtendYokee.Query().
//		GroupBy(carextendyokee.FieldDeleteTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ceyq *CarExtendYokeeQuery) GroupBy(field string, fields ...string) *CarExtendYokeeGroupBy {
	ceyq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CarExtendYokeeGroupBy{build: ceyq}
	grbuild.flds = &ceyq.ctx.Fields
	grbuild.label = carextendyokee.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeleteTime time.Time `json:"delete_time,omitempty"`
//	}
//
//	client.CarExtendYokee.Query().
//		Select(carextendyokee.FieldDeleteTime).
//		Scan(ctx, &v)
func (ceyq *CarExtendYokeeQuery) Select(fields ...string) *CarExtendYokeeSelect {
	ceyq.ctx.Fields = append(ceyq.ctx.Fields, fields...)
	sbuild := &CarExtendYokeeSelect{CarExtendYokeeQuery: ceyq}
	sbuild.label = carextendyokee.Label
	sbuild.flds, sbuild.scan = &ceyq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CarExtendYokeeSelect configured with the given aggregations.
func (ceyq *CarExtendYokeeQuery) Aggregate(fns ...AggregateFunc) *CarExtendYokeeSelect {
	return ceyq.Select().Aggregate(fns...)
}

func (ceyq *CarExtendYokeeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ceyq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ceyq); err != nil {
				return err
			}
		}
	}
	for _, f := range ceyq.ctx.Fields {
		if !carextendyokee.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ceyq.path != nil {
		prev, err := ceyq.path(ctx)
		if err != nil {
			return err
		}
		ceyq.sql = prev
	}
	return nil
}

func (ceyq *CarExtendYokeeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CarExtendYokee, error) {
	var (
		nodes = []*CarExtendYokee{}
		_spec = ceyq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CarExtendYokee).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CarExtendYokee{config: ceyq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ceyq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ceyq *CarExtendYokeeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ceyq.querySpec()
	_spec.Node.Columns = ceyq.ctx.Fields
	if len(ceyq.ctx.Fields) > 0 {
		_spec.Unique = ceyq.ctx.Unique != nil && *ceyq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ceyq.driver, _spec)
}

func (ceyq *CarExtendYokeeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(carextendyokee.Table, carextendyokee.Columns, sqlgraph.NewFieldSpec(carextendyokee.FieldID, field.TypeInt))
	_spec.From = ceyq.sql
	if unique := ceyq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ceyq.path != nil {
		_spec.Unique = true
	}
	if fields := ceyq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, carextendyokee.FieldID)
		for i := range fields {
			if fields[i] != carextendyokee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ceyq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ceyq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ceyq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ceyq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ceyq *CarExtendYokeeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ceyq.driver.Dialect())
	t1 := builder.Table(carextendyokee.Table)
	columns := ceyq.ctx.Fields
	if len(columns) == 0 {
		columns = carextendyokee.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ceyq.sql != nil {
		selector = ceyq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ceyq.ctx.Unique != nil && *ceyq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ceyq.predicates {
		p(selector)
	}
	for _, p := range ceyq.order {
		p(selector)
	}
	if offset := ceyq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ceyq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CarExtendYokeeGroupBy is the group-by builder for CarExtendYokee entities.
type CarExtendYokeeGroupBy struct {
	selector
	build *CarExtendYokeeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ceygb *CarExtendYokeeGroupBy) Aggregate(fns ...AggregateFunc) *CarExtendYokeeGroupBy {
	ceygb.fns = append(ceygb.fns, fns...)
	return ceygb
}

// Scan applies the selector query and scans the result into the given value.
func (ceygb *CarExtendYokeeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ceygb.build.ctx, ent.OpQueryGroupBy)
	if err := ceygb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarExtendYokeeQuery, *CarExtendYokeeGroupBy](ctx, ceygb.build, ceygb, ceygb.build.inters, v)
}

func (ceygb *CarExtendYokeeGroupBy) sqlScan(ctx context.Context, root *CarExtendYokeeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ceygb.fns))
	for _, fn := range ceygb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ceygb.flds)+len(ceygb.fns))
		for _, f := range *ceygb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ceygb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ceygb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CarExtendYokeeSelect is the builder for selecting fields of CarExtendYokee entities.
type CarExtendYokeeSelect struct {
	*CarExtendYokeeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ceys *CarExtendYokeeSelect) Aggregate(fns ...AggregateFunc) *CarExtendYokeeSelect {
	ceys.fns = append(ceys.fns, fns...)
	return ceys
}

// Scan applies the selector query and scans the result into the given value.
func (ceys *CarExtendYokeeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ceys.ctx, ent.OpQuerySelect)
	if err := ceys.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CarExtendYokeeQuery, *CarExtendYokeeSelect](ctx, ceys.CarExtendYokeeQuery, ceys, ceys.inters, v)
}

func (ceys *CarExtendYokeeSelect) sqlScan(ctx context.Context, root *CarExtendYokeeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ceys.fns))
	for _, fn := range ceys.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ceys.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ceys.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
