// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"github.com/jianbo-zh/jydata/database/ent/carsmodels"
	"github.com/jianbo-zh/jydata/database/ent/carsmodelsgroups"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CarsModelsGroups is the model entity for the CarsModelsGroups schema.
type CarsModelsGroups struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 型号ID
	ModelID int `json:"model_id,omitempty"`
	// 分组备注
	GroupRemark string `json:"group_remark,omitempty"`
	// 参数名称
	GroupName string `json:"group_name,omitempty"`
	// 状态：0 - 不可用，1 - 可用
	Status int `json:"status,omitempty"`
	// 是否已删除：0 - 正常，1 - 已删除
	IsDeleted int `json:"is_deleted,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CarsModelsGroupsQuery when eager-loading is set.
	Edges        CarsModelsGroupsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CarsModelsGroupsEdges holds the relations/edges for other nodes in the graph.
type CarsModelsGroupsEdges struct {
	// Model holds the value of the model edge.
	Model *CarsModels `json:"model,omitempty"`
	// Params holds the value of the params edge.
	Params []*CarsModelsGroupsParams `json:"params,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ModelOrErr returns the Model value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CarsModelsGroupsEdges) ModelOrErr() (*CarsModels, error) {
	if e.Model != nil {
		return e.Model, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: carsmodels.Label}
	}
	return nil, &NotLoadedError{edge: "model"}
}

// ParamsOrErr returns the Params value or an error if the edge
// was not loaded in eager-loading.
func (e CarsModelsGroupsEdges) ParamsOrErr() ([]*CarsModelsGroupsParams, error) {
	if e.loadedTypes[1] {
		return e.Params, nil
	}
	return nil, &NotLoadedError{edge: "params"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CarsModelsGroups) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case carsmodelsgroups.FieldID, carsmodelsgroups.FieldModelID, carsmodelsgroups.FieldStatus, carsmodelsgroups.FieldIsDeleted:
			values[i] = new(sql.NullInt64)
		case carsmodelsgroups.FieldGroupRemark, carsmodelsgroups.FieldGroupName:
			values[i] = new(sql.NullString)
		case carsmodelsgroups.FieldCreateTime, carsmodelsgroups.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CarsModelsGroups fields.
func (cmg *CarsModelsGroups) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case carsmodelsgroups.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cmg.ID = int(value.Int64)
		case carsmodelsgroups.FieldModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				cmg.ModelID = int(value.Int64)
			}
		case carsmodelsgroups.FieldGroupRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_remark", values[i])
			} else if value.Valid {
				cmg.GroupRemark = value.String
			}
		case carsmodelsgroups.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				cmg.GroupName = value.String
			}
		case carsmodelsgroups.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				cmg.Status = int(value.Int64)
			}
		case carsmodelsgroups.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				cmg.IsDeleted = int(value.Int64)
			}
		case carsmodelsgroups.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				cmg.CreateTime = value.Time
			}
		case carsmodelsgroups.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				cmg.UpdateTime = value.Time
			}
		default:
			cmg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CarsModelsGroups.
// This includes values selected through modifiers, order, etc.
func (cmg *CarsModelsGroups) Value(name string) (ent.Value, error) {
	return cmg.selectValues.Get(name)
}

// QueryModel queries the "model" edge of the CarsModelsGroups entity.
func (cmg *CarsModelsGroups) QueryModel() *CarsModelsQuery {
	return NewCarsModelsGroupsClient(cmg.config).QueryModel(cmg)
}

// QueryParams queries the "params" edge of the CarsModelsGroups entity.
func (cmg *CarsModelsGroups) QueryParams() *CarsModelsGroupsParamsQuery {
	return NewCarsModelsGroupsClient(cmg.config).QueryParams(cmg)
}

// Update returns a builder for updating this CarsModelsGroups.
// Note that you need to call CarsModelsGroups.Unwrap() before calling this method if this CarsModelsGroups
// was returned from a transaction, and the transaction was committed or rolled back.
func (cmg *CarsModelsGroups) Update() *CarsModelsGroupsUpdateOne {
	return NewCarsModelsGroupsClient(cmg.config).UpdateOne(cmg)
}

// Unwrap unwraps the CarsModelsGroups entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cmg *CarsModelsGroups) Unwrap() *CarsModelsGroups {
	_tx, ok := cmg.config.driver.(*txDriver)
	if !ok {
		panic("ent: CarsModelsGroups is not a transactional entity")
	}
	cmg.config.driver = _tx.drv
	return cmg
}

// String implements the fmt.Stringer.
func (cmg *CarsModelsGroups) String() string {
	var builder strings.Builder
	builder.WriteString("CarsModelsGroups(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cmg.ID))
	builder.WriteString("model_id=")
	builder.WriteString(fmt.Sprintf("%v", cmg.ModelID))
	builder.WriteString(", ")
	builder.WriteString("group_remark=")
	builder.WriteString(cmg.GroupRemark)
	builder.WriteString(", ")
	builder.WriteString("group_name=")
	builder.WriteString(cmg.GroupName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", cmg.Status))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", cmg.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(cmg.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(cmg.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CarsModelsGroupsSlice is a parsable slice of CarsModelsGroups.
type CarsModelsGroupsSlice []*CarsModelsGroups
