// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"github.com/jianbo-zh/jydata/database/ent/order"
	"github.com/jianbo-zh/jydata/database/ent/orderbilling"
	"github.com/jianbo-zh/jydata/database/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderBillingQuery is the builder for querying OrderBilling entities.
type OrderBillingQuery struct {
	config
	ctx        *QueryContext
	order      []orderbilling.OrderOption
	inters     []Interceptor
	predicates []predicate.OrderBilling
	withOrder  *OrderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderBillingQuery builder.
func (obq *OrderBillingQuery) Where(ps ...predicate.OrderBilling) *OrderBillingQuery {
	obq.predicates = append(obq.predicates, ps...)
	return obq
}

// Limit the number of records to be returned by this query.
func (obq *OrderBillingQuery) Limit(limit int) *OrderBillingQuery {
	obq.ctx.Limit = &limit
	return obq
}

// Offset to start from.
func (obq *OrderBillingQuery) Offset(offset int) *OrderBillingQuery {
	obq.ctx.Offset = &offset
	return obq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (obq *OrderBillingQuery) Unique(unique bool) *OrderBillingQuery {
	obq.ctx.Unique = &unique
	return obq
}

// Order specifies how the records should be ordered.
func (obq *OrderBillingQuery) Order(o ...orderbilling.OrderOption) *OrderBillingQuery {
	obq.order = append(obq.order, o...)
	return obq
}

// QueryOrder chains the current query on the "order" edge.
func (obq *OrderBillingQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: obq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := obq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := obq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderbilling.Table, orderbilling.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, orderbilling.OrderTable, orderbilling.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(obq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrderBilling entity from the query.
// Returns a *NotFoundError when no OrderBilling was found.
func (obq *OrderBillingQuery) First(ctx context.Context) (*OrderBilling, error) {
	nodes, err := obq.Limit(1).All(setContextOp(ctx, obq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderbilling.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (obq *OrderBillingQuery) FirstX(ctx context.Context) *OrderBilling {
	node, err := obq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderBilling ID from the query.
// Returns a *NotFoundError when no OrderBilling ID was found.
func (obq *OrderBillingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = obq.Limit(1).IDs(setContextOp(ctx, obq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderbilling.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (obq *OrderBillingQuery) FirstIDX(ctx context.Context) int {
	id, err := obq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderBilling entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderBilling entity is found.
// Returns a *NotFoundError when no OrderBilling entities are found.
func (obq *OrderBillingQuery) Only(ctx context.Context) (*OrderBilling, error) {
	nodes, err := obq.Limit(2).All(setContextOp(ctx, obq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderbilling.Label}
	default:
		return nil, &NotSingularError{orderbilling.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (obq *OrderBillingQuery) OnlyX(ctx context.Context) *OrderBilling {
	node, err := obq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderBilling ID in the query.
// Returns a *NotSingularError when more than one OrderBilling ID is found.
// Returns a *NotFoundError when no entities are found.
func (obq *OrderBillingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = obq.Limit(2).IDs(setContextOp(ctx, obq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderbilling.Label}
	default:
		err = &NotSingularError{orderbilling.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (obq *OrderBillingQuery) OnlyIDX(ctx context.Context) int {
	id, err := obq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderBillings.
func (obq *OrderBillingQuery) All(ctx context.Context) ([]*OrderBilling, error) {
	ctx = setContextOp(ctx, obq.ctx, ent.OpQueryAll)
	if err := obq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderBilling, *OrderBillingQuery]()
	return withInterceptors[[]*OrderBilling](ctx, obq, qr, obq.inters)
}

// AllX is like All, but panics if an error occurs.
func (obq *OrderBillingQuery) AllX(ctx context.Context) []*OrderBilling {
	nodes, err := obq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderBilling IDs.
func (obq *OrderBillingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if obq.ctx.Unique == nil && obq.path != nil {
		obq.Unique(true)
	}
	ctx = setContextOp(ctx, obq.ctx, ent.OpQueryIDs)
	if err = obq.Select(orderbilling.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (obq *OrderBillingQuery) IDsX(ctx context.Context) []int {
	ids, err := obq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (obq *OrderBillingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, obq.ctx, ent.OpQueryCount)
	if err := obq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, obq, querierCount[*OrderBillingQuery](), obq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (obq *OrderBillingQuery) CountX(ctx context.Context) int {
	count, err := obq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (obq *OrderBillingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, obq.ctx, ent.OpQueryExist)
	switch _, err := obq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (obq *OrderBillingQuery) ExistX(ctx context.Context) bool {
	exist, err := obq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderBillingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (obq *OrderBillingQuery) Clone() *OrderBillingQuery {
	if obq == nil {
		return nil
	}
	return &OrderBillingQuery{
		config:     obq.config,
		ctx:        obq.ctx.Clone(),
		order:      append([]orderbilling.OrderOption{}, obq.order...),
		inters:     append([]Interceptor{}, obq.inters...),
		predicates: append([]predicate.OrderBilling{}, obq.predicates...),
		withOrder:  obq.withOrder.Clone(),
		// clone intermediate query.
		sql:  obq.sql.Clone(),
		path: obq.path,
	}
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (obq *OrderBillingQuery) WithOrder(opts ...func(*OrderQuery)) *OrderBillingQuery {
	query := (&OrderClient{config: obq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	obq.withOrder = query
	return obq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderID int `json:"order_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderBilling.Query().
//		GroupBy(orderbilling.FieldOrderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (obq *OrderBillingQuery) GroupBy(field string, fields ...string) *OrderBillingGroupBy {
	obq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderBillingGroupBy{build: obq}
	grbuild.flds = &obq.ctx.Fields
	grbuild.label = orderbilling.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderID int `json:"order_id,omitempty"`
//	}
//
//	client.OrderBilling.Query().
//		Select(orderbilling.FieldOrderID).
//		Scan(ctx, &v)
func (obq *OrderBillingQuery) Select(fields ...string) *OrderBillingSelect {
	obq.ctx.Fields = append(obq.ctx.Fields, fields...)
	sbuild := &OrderBillingSelect{OrderBillingQuery: obq}
	sbuild.label = orderbilling.Label
	sbuild.flds, sbuild.scan = &obq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderBillingSelect configured with the given aggregations.
func (obq *OrderBillingQuery) Aggregate(fns ...AggregateFunc) *OrderBillingSelect {
	return obq.Select().Aggregate(fns...)
}

func (obq *OrderBillingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range obq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, obq); err != nil {
				return err
			}
		}
	}
	for _, f := range obq.ctx.Fields {
		if !orderbilling.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if obq.path != nil {
		prev, err := obq.path(ctx)
		if err != nil {
			return err
		}
		obq.sql = prev
	}
	return nil
}

func (obq *OrderBillingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderBilling, error) {
	var (
		nodes       = []*OrderBilling{}
		_spec       = obq.querySpec()
		loadedTypes = [1]bool{
			obq.withOrder != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderBilling).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderBilling{config: obq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, obq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := obq.withOrder; query != nil {
		if err := obq.loadOrder(ctx, query, nodes, nil,
			func(n *OrderBilling, e *Order) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (obq *OrderBillingQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*OrderBilling, init func(*OrderBilling), assign func(*OrderBilling, *Order)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrderBilling)
	for i := range nodes {
		fk := nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(order.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (obq *OrderBillingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := obq.querySpec()
	_spec.Node.Columns = obq.ctx.Fields
	if len(obq.ctx.Fields) > 0 {
		_spec.Unique = obq.ctx.Unique != nil && *obq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, obq.driver, _spec)
}

func (obq *OrderBillingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orderbilling.Table, orderbilling.Columns, sqlgraph.NewFieldSpec(orderbilling.FieldID, field.TypeInt))
	_spec.From = obq.sql
	if unique := obq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if obq.path != nil {
		_spec.Unique = true
	}
	if fields := obq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderbilling.FieldID)
		for i := range fields {
			if fields[i] != orderbilling.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if obq.withOrder != nil {
			_spec.Node.AddColumnOnce(orderbilling.FieldOrderID)
		}
	}
	if ps := obq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := obq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := obq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := obq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (obq *OrderBillingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(obq.driver.Dialect())
	t1 := builder.Table(orderbilling.Table)
	columns := obq.ctx.Fields
	if len(columns) == 0 {
		columns = orderbilling.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if obq.sql != nil {
		selector = obq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if obq.ctx.Unique != nil && *obq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range obq.predicates {
		p(selector)
	}
	for _, p := range obq.order {
		p(selector)
	}
	if offset := obq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := obq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderBillingGroupBy is the group-by builder for OrderBilling entities.
type OrderBillingGroupBy struct {
	selector
	build *OrderBillingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (obgb *OrderBillingGroupBy) Aggregate(fns ...AggregateFunc) *OrderBillingGroupBy {
	obgb.fns = append(obgb.fns, fns...)
	return obgb
}

// Scan applies the selector query and scans the result into the given value.
func (obgb *OrderBillingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, obgb.build.ctx, ent.OpQueryGroupBy)
	if err := obgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderBillingQuery, *OrderBillingGroupBy](ctx, obgb.build, obgb, obgb.build.inters, v)
}

func (obgb *OrderBillingGroupBy) sqlScan(ctx context.Context, root *OrderBillingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(obgb.fns))
	for _, fn := range obgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*obgb.flds)+len(obgb.fns))
		for _, f := range *obgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*obgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := obgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderBillingSelect is the builder for selecting fields of OrderBilling entities.
type OrderBillingSelect struct {
	*OrderBillingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (obs *OrderBillingSelect) Aggregate(fns ...AggregateFunc) *OrderBillingSelect {
	obs.fns = append(obs.fns, fns...)
	return obs
}

// Scan applies the selector query and scans the result into the given value.
func (obs *OrderBillingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, obs.ctx, ent.OpQuerySelect)
	if err := obs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderBillingQuery, *OrderBillingSelect](ctx, obs.OrderBillingQuery, obs, obs.inters, v)
}

func (obs *OrderBillingSelect) sqlScan(ctx context.Context, root *OrderBillingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(obs.fns))
	for _, fn := range obs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*obs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := obs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
