// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jianbo-zh/jydata/database/ent/poiextendyokee"
	"github.com/jianbo-zh/jydata/database/ent/predicate"
)

// PoiExtendYokeeQuery is the builder for querying PoiExtendYokee entities.
type PoiExtendYokeeQuery struct {
	config
	ctx        *QueryContext
	order      []poiextendyokee.OrderOption
	inters     []Interceptor
	predicates []predicate.PoiExtendYokee
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PoiExtendYokeeQuery builder.
func (peyq *PoiExtendYokeeQuery) Where(ps ...predicate.PoiExtendYokee) *PoiExtendYokeeQuery {
	peyq.predicates = append(peyq.predicates, ps...)
	return peyq
}

// Limit the number of records to be returned by this query.
func (peyq *PoiExtendYokeeQuery) Limit(limit int) *PoiExtendYokeeQuery {
	peyq.ctx.Limit = &limit
	return peyq
}

// Offset to start from.
func (peyq *PoiExtendYokeeQuery) Offset(offset int) *PoiExtendYokeeQuery {
	peyq.ctx.Offset = &offset
	return peyq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (peyq *PoiExtendYokeeQuery) Unique(unique bool) *PoiExtendYokeeQuery {
	peyq.ctx.Unique = &unique
	return peyq
}

// Order specifies how the records should be ordered.
func (peyq *PoiExtendYokeeQuery) Order(o ...poiextendyokee.OrderOption) *PoiExtendYokeeQuery {
	peyq.order = append(peyq.order, o...)
	return peyq
}

// First returns the first PoiExtendYokee entity from the query.
// Returns a *NotFoundError when no PoiExtendYokee was found.
func (peyq *PoiExtendYokeeQuery) First(ctx context.Context) (*PoiExtendYokee, error) {
	nodes, err := peyq.Limit(1).All(setContextOp(ctx, peyq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{poiextendyokee.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) FirstX(ctx context.Context) *PoiExtendYokee {
	node, err := peyq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PoiExtendYokee ID from the query.
// Returns a *NotFoundError when no PoiExtendYokee ID was found.
func (peyq *PoiExtendYokeeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = peyq.Limit(1).IDs(setContextOp(ctx, peyq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{poiextendyokee.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) FirstIDX(ctx context.Context) int {
	id, err := peyq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PoiExtendYokee entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PoiExtendYokee entity is found.
// Returns a *NotFoundError when no PoiExtendYokee entities are found.
func (peyq *PoiExtendYokeeQuery) Only(ctx context.Context) (*PoiExtendYokee, error) {
	nodes, err := peyq.Limit(2).All(setContextOp(ctx, peyq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{poiextendyokee.Label}
	default:
		return nil, &NotSingularError{poiextendyokee.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) OnlyX(ctx context.Context) *PoiExtendYokee {
	node, err := peyq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PoiExtendYokee ID in the query.
// Returns a *NotSingularError when more than one PoiExtendYokee ID is found.
// Returns a *NotFoundError when no entities are found.
func (peyq *PoiExtendYokeeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = peyq.Limit(2).IDs(setContextOp(ctx, peyq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{poiextendyokee.Label}
	default:
		err = &NotSingularError{poiextendyokee.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) OnlyIDX(ctx context.Context) int {
	id, err := peyq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PoiExtendYokees.
func (peyq *PoiExtendYokeeQuery) All(ctx context.Context) ([]*PoiExtendYokee, error) {
	ctx = setContextOp(ctx, peyq.ctx, ent.OpQueryAll)
	if err := peyq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PoiExtendYokee, *PoiExtendYokeeQuery]()
	return withInterceptors[[]*PoiExtendYokee](ctx, peyq, qr, peyq.inters)
}

// AllX is like All, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) AllX(ctx context.Context) []*PoiExtendYokee {
	nodes, err := peyq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PoiExtendYokee IDs.
func (peyq *PoiExtendYokeeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if peyq.ctx.Unique == nil && peyq.path != nil {
		peyq.Unique(true)
	}
	ctx = setContextOp(ctx, peyq.ctx, ent.OpQueryIDs)
	if err = peyq.Select(poiextendyokee.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) IDsX(ctx context.Context) []int {
	ids, err := peyq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (peyq *PoiExtendYokeeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, peyq.ctx, ent.OpQueryCount)
	if err := peyq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, peyq, querierCount[*PoiExtendYokeeQuery](), peyq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) CountX(ctx context.Context) int {
	count, err := peyq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (peyq *PoiExtendYokeeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, peyq.ctx, ent.OpQueryExist)
	switch _, err := peyq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (peyq *PoiExtendYokeeQuery) ExistX(ctx context.Context) bool {
	exist, err := peyq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PoiExtendYokeeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (peyq *PoiExtendYokeeQuery) Clone() *PoiExtendYokeeQuery {
	if peyq == nil {
		return nil
	}
	return &PoiExtendYokeeQuery{
		config:     peyq.config,
		ctx:        peyq.ctx.Clone(),
		order:      append([]poiextendyokee.OrderOption{}, peyq.order...),
		inters:     append([]Interceptor{}, peyq.inters...),
		predicates: append([]predicate.PoiExtendYokee{}, peyq.predicates...),
		// clone intermediate query.
		sql:  peyq.sql.Clone(),
		path: peyq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PoiID int `json:"poi_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PoiExtendYokee.Query().
//		GroupBy(poiextendyokee.FieldPoiID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (peyq *PoiExtendYokeeQuery) GroupBy(field string, fields ...string) *PoiExtendYokeeGroupBy {
	peyq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PoiExtendYokeeGroupBy{build: peyq}
	grbuild.flds = &peyq.ctx.Fields
	grbuild.label = poiextendyokee.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PoiID int `json:"poi_id,omitempty"`
//	}
//
//	client.PoiExtendYokee.Query().
//		Select(poiextendyokee.FieldPoiID).
//		Scan(ctx, &v)
func (peyq *PoiExtendYokeeQuery) Select(fields ...string) *PoiExtendYokeeSelect {
	peyq.ctx.Fields = append(peyq.ctx.Fields, fields...)
	sbuild := &PoiExtendYokeeSelect{PoiExtendYokeeQuery: peyq}
	sbuild.label = poiextendyokee.Label
	sbuild.flds, sbuild.scan = &peyq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PoiExtendYokeeSelect configured with the given aggregations.
func (peyq *PoiExtendYokeeQuery) Aggregate(fns ...AggregateFunc) *PoiExtendYokeeSelect {
	return peyq.Select().Aggregate(fns...)
}

func (peyq *PoiExtendYokeeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range peyq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, peyq); err != nil {
				return err
			}
		}
	}
	for _, f := range peyq.ctx.Fields {
		if !poiextendyokee.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if peyq.path != nil {
		prev, err := peyq.path(ctx)
		if err != nil {
			return err
		}
		peyq.sql = prev
	}
	return nil
}

func (peyq *PoiExtendYokeeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PoiExtendYokee, error) {
	var (
		nodes = []*PoiExtendYokee{}
		_spec = peyq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PoiExtendYokee).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PoiExtendYokee{config: peyq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, peyq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (peyq *PoiExtendYokeeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := peyq.querySpec()
	_spec.Node.Columns = peyq.ctx.Fields
	if len(peyq.ctx.Fields) > 0 {
		_spec.Unique = peyq.ctx.Unique != nil && *peyq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, peyq.driver, _spec)
}

func (peyq *PoiExtendYokeeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(poiextendyokee.Table, poiextendyokee.Columns, sqlgraph.NewFieldSpec(poiextendyokee.FieldID, field.TypeInt))
	_spec.From = peyq.sql
	if unique := peyq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if peyq.path != nil {
		_spec.Unique = true
	}
	if fields := peyq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, poiextendyokee.FieldID)
		for i := range fields {
			if fields[i] != poiextendyokee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := peyq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := peyq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := peyq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := peyq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (peyq *PoiExtendYokeeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(peyq.driver.Dialect())
	t1 := builder.Table(poiextendyokee.Table)
	columns := peyq.ctx.Fields
	if len(columns) == 0 {
		columns = poiextendyokee.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if peyq.sql != nil {
		selector = peyq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if peyq.ctx.Unique != nil && *peyq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range peyq.predicates {
		p(selector)
	}
	for _, p := range peyq.order {
		p(selector)
	}
	if offset := peyq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := peyq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PoiExtendYokeeGroupBy is the group-by builder for PoiExtendYokee entities.
type PoiExtendYokeeGroupBy struct {
	selector
	build *PoiExtendYokeeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (peygb *PoiExtendYokeeGroupBy) Aggregate(fns ...AggregateFunc) *PoiExtendYokeeGroupBy {
	peygb.fns = append(peygb.fns, fns...)
	return peygb
}

// Scan applies the selector query and scans the result into the given value.
func (peygb *PoiExtendYokeeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, peygb.build.ctx, ent.OpQueryGroupBy)
	if err := peygb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PoiExtendYokeeQuery, *PoiExtendYokeeGroupBy](ctx, peygb.build, peygb, peygb.build.inters, v)
}

func (peygb *PoiExtendYokeeGroupBy) sqlScan(ctx context.Context, root *PoiExtendYokeeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(peygb.fns))
	for _, fn := range peygb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*peygb.flds)+len(peygb.fns))
		for _, f := range *peygb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*peygb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := peygb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PoiExtendYokeeSelect is the builder for selecting fields of PoiExtendYokee entities.
type PoiExtendYokeeSelect struct {
	*PoiExtendYokeeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (peys *PoiExtendYokeeSelect) Aggregate(fns ...AggregateFunc) *PoiExtendYokeeSelect {
	peys.fns = append(peys.fns, fns...)
	return peys
}

// Scan applies the selector query and scans the result into the given value.
func (peys *PoiExtendYokeeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, peys.ctx, ent.OpQuerySelect)
	if err := peys.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PoiExtendYokeeQuery, *PoiExtendYokeeSelect](ctx, peys.PoiExtendYokeeQuery, peys, peys.inters, v)
}

func (peys *PoiExtendYokeeSelect) sqlScan(ctx context.Context, root *PoiExtendYokeeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(peys.fns))
	for _, fn := range peys.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*peys.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := peys.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
